[package]
name = "match-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)', 'cfg(coverage_nightly)'] }

[dependencies]
match-protocol = { path = "../match-protocol" }
smol_str = { version = "0.2", features = ["serde"] }
smallvec = "1"
bigdecimal = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
